novoProjeto/accounts/urls.py
from django.conf.urls import url, include
# from simplemooc.accounts.views import index
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import path
from novoProjeto.accounts.views import register, dashboard, edit, edit_password, password_reset, password_reset_confirm

# from novoProjeto.accounts.views import edit_password

urlpatterns = [
    path('entrar/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('cadastre-se/', register, name='register'),
    path('nova-senha/', password_reset, name='password_reset'),
    #path('confirmar-nova-senha/(?P<key>\w+)/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^confirmar-nova-senha/(?P<key>[\w_-]+)/$', password_reset_confirm, name='password_reset_confirm'),
    path('sair/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('', dashboard, name='dashboard'),
    path('editar/', edit, name='edit'),
    path('editar-password/', edit_password, name='edit_password'),

]

novoProjeto/core/urls.py
from django.conf.urls import url
from django.urls import path
from novoProjeto.core.views import home
from novoProjeto.core.views import contact

urlpatterns = [
    path('', home, name='home'),
    path('contato/', contact, name='contact'),
]

novoProjeto/courses/urls.py
from django.conf.urls import url
from novoProjeto.courses.views import (index, details, enrollment, announcements, undo_enrollment, show_announcement,
                                       lessons, lesson, material)

urlpatterns = [
    url(r'^$', index, name='index'),
    #url(r'^(?P<pk>\d+)/$', details, name='details'),
    url(r'^(?P<slug>[\w_-]+)/$', details, name='details'),
    url(r'^(?P<slug>[\w_-]+)/inscricao/$', enrollment, name='enrollment'),
    url(r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$', undo_enrollment, name='undo_enrollment'),
    url(r'^(?P<slug>[\w_-]+)/anuncios/$', announcements, name='announcements'),
    url(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', show_announcement, name='show_announcement'),
    url(r'^(?P<slug>[\w_-]+)/aulas/$', lessons, name='lessons'),
    url(r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$', lesson, name='lesson'),
    url(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', material, name='material'),
]

novoProjeto/novoProjeto/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

novoProjeto/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include(('novoProjeto.core.urls', 'core'), namespace='core')),
    url(r'^conta/', include(('novoProjeto.accounts.urls','accounts'), namespace='accounts')),
    url(r'^cursos/', include(('novoProjeto.courses.urls', 'courses'), namespace='courses')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

novoProjeto/core/models.py
from django.db import models

# Create your models here.

novoProjeto/core/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request, 'home.html')


def contact(request):
    return render(request, 'contact.html')

novoProjeto/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="PUC Online - Plataforma de apoio ao aluno" />
    <title>PUC Online</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        .w3-bar .w3-button {
            padding: 16px;
        }
        .chama {

        }

    </style>

</head>
<body>
<!-- Codigo antigo
<div class="header">
    <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
        <a class="pure-menu-heading" href="{% url 'core:home' %}">PUC Online</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:dashboard'%}">Painel</a></li>
            <li><a href="{% url 'accounts:logout'%}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login'%}">Entrar</a></li>
            {% endif %}

        </ul>
    </div>
</div>
-->
<div class="w3-top">
  <div class="w3-bar w3-white w3-card" id="myNavbar">
    <a href="{% url 'core:home' %}" class="w3-bar-item w3-button w3-wide">PUC-On</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
        <a href="{% url 'core:home' %}" class="w3-bar-item w3-button">INICIO</a>
        <a href="{% url 'courses:index' %}" class="w3-bar-item w3-button"><i class="fa fa-book"></i> CURSOS</a>
        <a href="{% url 'core:contact' %}" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i> CONTATO</a>
        {% if user.is_authenticated %}
        <a href="{% url 'accounts:dashboard'%}" class="w3-bar-item w3-button"><i class="fa fa-th"></i> PAINEL</a>
        <a href="{% url 'accounts:logout'%}" class="w3-bar-item w3-button"><i class="fa fa-close"></i> SAIR</a>
        {% else %}
        <a href="{% url 'accounts:login'%}" class="w3-bar-item w3-button"><i class="fa fa-home"></i> ENTRAR</a>
        {% endif %}
    </div>
  </div>
</div>
<div class="content">
    {% if messages %}
        <div class="pure-g-r content-ribbon">
            <aside class="pure-u-1">
                {% for message in messages %}
                <p>{{ message }}</p>
                {% endfor %}
            </aside>
        </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
        PUC Online - Plataforma de apoio ao aluno
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

novoProjeto/core/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Fale conosco</h1>
        <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
        <h4>Links</h4>
        <ul>
            <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@puconline.edu</a></li>
            <li>Twitter: <a href="https://twitter.com/simplemooc">@puconline</a></li>
        </ul>
    </div>
</div>

</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script><div id="yui3-css-stamp" style="position: absolute !important; visibility: hidden !important"></div>

</body>
</html>
{% endblock %}

novoProjeto/core/templates/home.html
<!DOCTYPE html>
<html>
<title>PUC-On</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

    body, html {
      height: 100%;
      line-height: 1.8;
    }

    /* Full height image header */
    .bgimg-1 {
      background-position: center;
      background-size: cover;
      background-image: url("https://cdn.pixabay.com/photo/2016/03/26/13/09/notebook-1280538_960_720.jpg");
      min-height: 100%;
    }

    .w3-bar .w3-button {
      padding: 16px;
    }
</style>
<body>

<nav class="w3-top">
    <div class="w3-bar w3-white w3-card" id="myNavbar">
    <a href="{% url 'core:home' %}" class="w3-bar-item w3-button w3-wide">PUC-On</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
        <a href="{% url 'core:home' %}" class="w3-bar-item w3-button">INICIO</a>
        <a href="{% url 'courses:index' %}" class="w3-bar-item w3-button"><i class="fa fa-book"></i> CURSOS</a>
        <a href="{% url 'core:contact' %}" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i> CONTATO</a>
        {% if user.is_authenticated %}
        <a href="{% url 'accounts:dashboard'%}" class="w3-bar-item w3-button"><i class="fa fa-th"></i> PAINEL</a>
        <a href="{% url 'accounts:logout'%}" class="w3-bar-item w3-button"><i class="fa fa-close"></i> SAIR</a>
        {% else %}
        <a href="{% url 'accounts:login'%}" class="w3-bar-item w3-button"><i class="fa fa-home"></i> ENTRAR</a>
        {% endif %}
    </div>
  </div>
</nav>

    <!-- Header with full-height image -->
    <header class="bgimg-1 w3-display-container w3-grayscale-min" id="home">
      <div class="w3-display-left w3-text-white" style="padding:48px">
        <span class="w3-jumbo w3-hide-small">Aprenda mais e melhor com a PUC-On</span><br>
        <span class="w3-xxlarge w3-hide-large w3-hide-medium">Aprenda melhor com a PUC-On</span><br>
        <span class="w3-large">Plataforma de apoio aos cursos presenciais da PUC Minas.</span>
        <p><a href="{% url 'courses:index' %}" class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity
        w3-hover-opacity-off">Acesse os cursos disponíveis</a></p>
      </div>
      <div class="w3-display-bottomleft w3-text-grey w3-large" style="padding:24px 48px">
        <i class="fa fa-facebook-official w3-hover-opacity"></i>
        <i class="fa fa-instagram w3-hover-opacity"></i>
        <i class="fa fa-linkedin w3-hover-opacity"></i>
      </div>
    </header>
</body>
</html>

novoProjeto/core/templates/new_home.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

body, html {
  height: 100%;
  line-height: 1.8;
}

/* Full height image header */
.bgimg-1 {
  background-position: center;
  background-size: cover;
  background-image: url("https://cdn.pixabay.com/photo/2016/03/26/13/09/notebook-1280538_960_720.jpg");
  min-height: 100%;
}

.w3-bar .w3-button {
  padding: 16px;
}
</style>
<body>

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-card" id="myNavbar">
    <a href="#home" class="w3-bar-item w3-button w3-wide">LOGO</a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      <a href="#about" class="w3-bar-item w3-button">ABOUT</a>
      <a href="#team" class="w3-bar-item w3-button"><i class="fa fa-user"></i> TEAM</a>
      <a href="#work" class="w3-bar-item w3-button"><i class="fa fa-th"></i> WORK</a>
      <a href="#pricing" class="w3-bar-item w3-button"><i class="fa fa-usd"></i> PRICING</a>
      <a href="#contact" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i> CONTACT</a>
    </div>
    <!-- Hide right-floated links on small screens and replace them with a menu icon -->

    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
      <i class="fa fa-bars"></i>
    </a>
  </div>
</div>

<!-- Header with full-height image -->
<header class="bgimg-1 w3-display-container w3-grayscale-min" id="home">
  <div class="w3-display-left w3-text-white" style="padding:48px">
    <span class="w3-jumbo w3-hide-small">Aprenda mais e melhor com o PUCOn</span><br>
    <span class="w3-xxlarge w3-hide-large w3-hide-medium">Aprende melhor com o PUCOn</span><br>
    <span class="w3-large">Plataforma de apoio aos cursos presenciais da PUC Minas.</span>
    <p><a href="{% url 'courses:index' %}" class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity
    w3-hover-opacity-off">Acesse os cursos disponíveis</a></p>
  </div>
  <div class="w3-display-bottomleft w3-text-grey w3-large" style="padding:24px 48px">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
  </div>
</header>
</body>
</html>


{% extends "base.html" %}

{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Aprenda mais e melhor utilizando esta plataforma de apoio da PUC Minas
                    </h1>
                    <h2 class="splash-subhead">
                        O PUC Online oferece cursos de apoio específicos para as matérias oferecidas presencialmente em todos os cursos de graduação e pós-graduação da universidade.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O PUCOn tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No PUCOn você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}